# arpeggios_bowing_exercise.py

filename = "arpeggios_bowing_etude.ly"

lilypond_code = r'''
\version "2.24.2"
\header {
  title = "Arpeggios & Bowing Study"
  subtitle = "Triplets + Eighths, 1st–5th Position on Violin"
  composer = "Generated by Python"
}

violin = \relative g, {
  \clef treble
  \key d \major
  \time 6/8
  \tempo "Triplets = Moderate" 8. = 84

  % === ARPEGGIOS IN TRIPLETS ===
  \mark \markup { \box "Arpeggios in Triplets – Shifting 1st to 5th Position" }

  \repeat volta 2 {
    % D Major
    g'16 b d  g b d |
    a16 cis e  a cis e |
    b16 d fis  b d fis |

    % Shift to 3rd Position
    d'16 fis a  d fis a |
    c'16 e g  c e g |

    % Shift to 5th Position
    e'16 g b  e g b |
    d'16 fis a  d fis a |
  }

  \bar "||"
  \break

  % === BOWING EXERCISES IN 5TH POSITION ===
  \time 3/8
  \tempo "Eighths = Even, Controlled" 8 = 72

  \mark \markup { \box "Bowing Exercise on G, D, A Strings – 5th Position" }

  \repeat volta 3 {
    % G string
    g8 g g |
    a8 a a |
    b8 b b |

    % D string
    d8 d d |
    e8 e e |
    fis8 fis fis |

    % A string
    a'8 a a |
    b8 b b |
    cis8 cis cis |
  }
}

\score {
  \new Staff \violin
  \layout { }
  \midi { }
}
'''

with open(filename, 'w') as file:
    file.write(lilypond_code)

print(f"LilyPond file '{filename}' generated successfully.")

