# double_stops_split_then_combined.py

filename = "double_stops_analysis.ly"

lilypond_code = r'''
\version "2.24.2"
\header {
  title = "Double-Stops: Separate Then Together"
  composer = "Generated by Python"
}

violin = \relative c' {
  \clef treble
  \key c \major
  \time 4/4

  % First double-stop: C and E
  e'4^\markup { \italic "Upper voice" }
  c4^\markup { \italic "Lower voice" }
  <c e'>2^\markup { \bold "Combined double-stop" }

  % Second double-stop: B and D
  d4
  b4
  <b d'>2

  % Third double-stop: A and C
  c4
  a4
  <a c'>2

  % Fourth double-stop: G and B
  b4
  g4
  <g b>2
}

\score {
  \new Staff \violin
  \layout { }
  \midi { \tempo 4 = 72 }
}
'''

with open(filename, 'w') as file:
    file.write(lilypond_code)

print(f"LilyPond file '{filename}' created successfully.")

