# violin_finger_shift_technique.py

filename = "no_slide_second_finger.ly"

lilypond_code = r'''
\version "2.24.2"
\header {
  title = "Finger Transition Study – Avoid Sliding 2nd Finger"
  subtitle = "Lift 2nd Finger for Shift to 5th Position"
  composer = "Generated by Python"
}

violin = \relative d' {
  \clef treble
  \key d \major
  \time 4/4
  \tempo "Andante" 4 = 66

  % First Position line
  d4^\markup { "1st pos – 1st finger" }
  e4^\markup { "2nd finger (do not shift from here)" }
  fis4^\markup { "3rd finger" }
  a4^\markup { "4th finger, prepare to shift" }

  % Lift 2nd finger; shift to 5th position
  \break
  b'4^\markup {
    \column {
      "Shift to 5th position"
      "2nd finger lifted before shift"
    }
  }
  cis4
  d4
  e4^\markup { "4th finger (5th pos)" }
}

\score {
  \new Staff \violin
  \layout { }
  \midi { \tempo 4 = 66 }
}
'''

with open(filename, 'w') as file:
    file.write(lilypond_code)

print(f"LilyPond file '{filename}' generated successfully.")

