# shift_4th_to_2nd_position.py

filename = "shift_4th_to_2nd_position.ly"

lilypond_code = r'''
\version "2.24.2"
\header {
  title = "Downward Shift Étude"
  subtitle = "From 4th to 2nd Position – Violin"
  composer = "Generated by Python"
}

violin = \relative a'' {
  \clef treble
  \key d \major
  \time 4/4
  \tempo "Lento" 4 = 60

  % Start in 4th position, A string
  a4^\markup { "4th position" }^\markup { \finger "1" }^\downbow
  g4^\markup { \finger "2" }^\upbow
  fis4^\markup { \finger "3" }^\downbow
  e4^\markup { \finger "4" }^\upbow

  % Prepare and execute shift to 2nd position
  \break
  d4^\markup { \column { "Shift ↓ to 2nd pos" "with lifted 2nd finger" } }^\markup { \finger "3" }^\downbow
  b4^\markup { \finger "2" }^\upbow
  a4^\markup { \finger "1" }^\downbow
  g4^\markup { \finger "3" }^\upbow
}

\score {
  \new Staff \violin
  \layout { }
  \midi { \tempo 4 = 60 }
}
'''

with open(filename, 'w') as file:
    file.write(lilypond_code)

print(f"LilyPond file '{filename}' generated successfully.")

