# shift_5th_to_2nd_position.py

filename = "shift_5th_to_2nd_position.ly"

lilypond_code = r'''
\version "2.24.2"
\header {
  title = "Downward Shift Étude"
  subtitle = "From 5th to 2nd Position – Violin"
  composer = "Generated by Python"
}

violin = \relative a'' {
  \clef treble
  \key d \major
  \time 4/4
  \tempo "Andante" 4 = 66

  % Begin in 5th position
  d4^\markup { "5th pos" }^\markup { \finger "1" }^\upbow
  c4^\markup { \column { "Shift ↓ to 2nd pos" "guide with 4st finger" "only 2 1/2 tone" } }^\markup { \finger "1" }^\downbow
  b4^\markup { \finger "1" }^\downbow

  a4^\markup { \finger "1" }^\downbow
  % Shift to 2nd position
  \break
  g4^\markup { \finger "2" }^\upbow
  fis4^\markup { \finger "3" }^\downbow
  

  e4^\markup { \finger "4" }^\upbow

  % Shift to 2nd position
  d4^\markup { \finger "1" }^\downbow
  b4^\markup { \finger "2" }^\upbow
  a4^\markup { \finger "3" }^\downbow
  g4^\markup { \finger "4" }^\upbow
}

\score {
  \new Staff \violin
  \layout { }
  \midi { \tempo 4 = 66 }
}
'''

with open(filename, 'w') as file:
    file.write(lilypond_code)

print(f"LilyPond file '{filename}' generated successfully.")

