# strike_finder_violin.py

filename = "strike_finder.ly"

lilypond_code = r'''
\version "2.24.2"
\header {
  title = "Strike-Finder Development"
  subtitle = "Double-Stops with Rhythmic Pulse"
  composer = "Generated by Python"
}

violin = \relative c' {
  \clef treble
  \key d \major
  \time 4/4

  % 1st pattern: First finger (E) + A drone in half note
  << {
    \voiceOne
    a'2~ a4 a % Upper voice sustained, last note strikes with lower
  } \\ {
    \voiceTwo
    e4 e8 e fis4 fis % Lower voice pulses in croches and noires
  } >>

  % 2nd pattern: 0 + 2
  << {
    \voiceOne
    d'2~ d4 d
  } \\ {
    \voiceTwo
    a4 a8 a b4 b
  } >>

  % 3rd pattern: 3rd finger + open A
  << {
    \voiceOne
    a'2~ a4 a
  } \\ {
    \voiceTwo
    d4 d8 d d4 d
  } >>

  % 4th pattern: 4th finger + G drone
  << {
    \voiceOne
    e'2~ e4 e
  } \\ {
    \voiceTwo
    g4 g8 a b4 b
  } >>
}

\score {
  \new Staff <<
    \new Voice = "violin" \violin
  >>
  \layout { }
  \midi { \tempo 4 = 88 }
}
\markup {
") The 15 preceding examples arc also to be executed
in semiquavers, in demise -
miquavers and in tremolo,
without definite number of
notes, quickly trilling."
}
'''

with open(filename, 'w') as file:
    file.write(lilypond_code)

print(f"LilyPond file '{filename}' created successfully.")

