# violin_first_position_bowing.py

filename = "first_position_bowing.ly"

lilypond_code = r'''
\version "2.24.2"
\header {
  title = "Violin First Position – Bowing & String Crossings"
  subtitle = "Bars repeated with bow angle transitions"
  composer = "Generated by Python"
}

violin = \relative c' {
  \clef treble
  \key d \major
  \time 4/4

  % Repeated section with single notes and bow annotations
  \repeat volta 3 {
    % G string (G position: flat arm, elevated elbow)
    g4^\markup { "G pos – elbow high" } r
    a4^\markup { "1st finger" } r
    b4 r
    c4 r^\markup { "Bow crosses to D string silently" }

    % D string (D position: 15° inclined)
    d4^\markup { "D pos – slight tilt" } r
    e4 r
    fis4 r
    g4 r^\markup { "Gradual move to A string" }

    % A string
    a4^\markup { "A pos – moderate tilt" } r
    b4 r
    cis4 r
    d4 r^\markup { "Smooth cross to E string" }

    % E string (15° incline, elbow low)
    e4^\markup { "E pos – lowest elbow angle" } r
    fis4 r
    gis4 r
    a4 r
  }

  % Visual rest measure for string-crossing practice
  r1^\markup {
    \column {
      "During rest: silently cross two or three strings."
      "Elbow and bow move gradually to new angle."
    }
  }
}

\score {
  \new Staff \violin
  \layout { }
  \midi { \tempo 4 = 72 }
}
'''

with open(filename, 'w') as file:
    file.write(lilypond_code)

print(f"LilyPond file '{filename}' created successfully.")

