# violin_double_stops_generator.py

filename = "violin_double_stops.ly"

lilypond_code = r'''
\version "2.24.2"
\header {
  title = "Analysis of Double-Stops on Violin"
  composer = "Generated by Python"
}

violin = \relative c' {
  \clef treble
  \key c \major
  \time 4/4

  % Open string double-stop
  <g d'>1^\markup { \bold "Open Fifth (G & D)" }

  % Thirds
  <a' c'>1^\markup { \bold "Minor Third (A & C)" }
  <b d'>1^\markup { \bold "Major Third (B & D)" }

  % Sixths
  <c e'>1^\markup { \bold "Major Sixth (C & E)" }
  <d f'>1^\markup { \bold "Minor Sixth (D & F)" }

  % Octaves
  <g g'>1^\markup { \bold "Octave (G & G')" }

  % Double-stops in a melodic phrase
  <c e'>4 <b d'> <a c'> <g b>^\markup { "Descending thirds" }

  % Harmonic context
  <c e'>1^\markup { \bold "Implied C major harmony" }
}

\score {
  \new Staff \violin
  \layout { }
  \midi { \tempo 4 = 60 }
}
'''

with open(filename, 'w') as file:
    file.write(lilypond_code)

print(f"LilyPond file '{filename}' created successfully.")

